export let strHeadline01="# 1级标题\n" +
  "\n" +
  "## 2级标题\n" +
  "\n" +
  "### 3级标题\n" +
  "\n" +
  "#### 4级标题\n" +
  "\n" +
  "##### 5级标题\n" +
  "\n" +
  "###### 6级标题\n" +
  "\n" +
  "Heading level 1\n" +
  "===============\n" +
  "\n" +
  "Heading level 2\n" +
  "---------------"
export let strParagraph="普通段落\n" +
  "\n" +
  "超长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长段落\n" +
  "\n" +
  "金庸小说中有许多经典文本，以下为你列举其中一段：\n" +
  "\n" +
  "杨过朗声说道：“今番良晤，豪兴不浅，他日江湖相逢，再当杯酒言欢。咱们就此别过。” 向一灯、周伯通、锳姑、黄药师、郭靖、黄蓉、点苍渔隐、武三通、朱子柳等各位前辈行礼拜别，和程英、陆无双表姊妹执手告别，转头对郭襄道：“小妹子，你好生保重，你如有何为难之事，虽无金针，仍可来要我为你办到。” 以前赠以三枚金针，答允郭襄办三件事，此时不赠金针，等于说不论多少难事，一概皆允，全不推辞。\n" +
  "\n" +
  "郭襄呜咽道：“多谢大哥哥！多谢杨大嫂！” 杨过再和耶律齐、郭芙、武氏兄弟夫妇挥手相别，袍袖一拂，携着小龙女之手，与神雕并肩下山。\n" +
  "\n" +
  "其时明月在天，清风吹叶，树巅乌鸦啊啊而鸣，郭襄再也忍耐不住，泪珠夺眶而出。正是：“秋风清，秋月明；落叶聚还散，寒鸦栖复惊。相思相见知何日，此时此夜难为情。”\n" +
  "\n" +
  "这段文字出自《神雕侠侣》第四十回，是杨过与众人离别时的场景，金庸通过对人物语言、动作的描写，以及 “明月”“清风”“乌鸦” 等环境元素的烘托，将郭襄对杨过的眷恋与不舍之情展现得淋漓尽致，画面感十足，令人动容。"
export let strDivider="内容\n" +
  "\n" +
  "---\n" +
  "\n" +
  "内容\n" +
  "\n" +
  "***\n" +
  "\n" +
  "内容\n" +
  "\n" +
  "--------------------\n" +
  "\n" +
  "内容\n" +
  "\n" +
  "***********************\n" +
  "\n" +
  "内容\n"

export let strLinebreak="软换行第一行\n" +
  "软换行第二行\n" +
  "\n" +
  "硬换行第一行  \n" +
  "硬换行第二行"
//数学公式
export let strformula="### 标题中数学公式 $a+b=c$\n"


export let strTable="### 最美数学公式 Top 100\n" +
  "\n" +
  "| 题号 | 标题 | 难易度 |\n" +
  "| :--- | ---:| :---: |\n" +
  "| 1 | aaaaaaaaaaaaaaaaaaaaa + bbbbbbbbbbbbbbbbbbbbbbb = c | 简单 |\n" +
  "| 15 | 三数之和 | [链接链接链接链接链接链接链接链接链接链接链接链接链接链接链接链接链接11](https://baidu.com) |\n" +
  "| 262 | 行程和用户 | 困难 |\n" +
  "\n" +
  "### 最美数学公式 Top 100\n" +
  "\n" +
  "| 序号 | 公式名称              | 数学公式                          | 描述                                                                 |\n" +
  "|------|-----------------------|-----------------------------------|----------------------------------------------------------------------|\n" +
  "| 101  | 同伦群长正合列            | \\cdots \\to \\pi_n(F) \\to \\pi_n(E) \\to \\pi_n(B) \\to \\pi_{n-1}(F) \\to \\cdots | 纤维丛拓扑结构的代数刻画                                             |\n" +
  "\n" +
  "---\n" +
  "\n" +
  "### 表格1\n" +
  "\n" +
  "| 题号 | 标题 | 难易度 |\n" +
  "| :--- | ---:| :---: |\n" +
  "| 1 | 两数之和 | 简单 |\n" +
  "| 15 | 三数之和 | 中等 |\n" +
  "| 262 | 行程和用户 | 困难 |\n" +
  "\n" +
  "### 表格2\n" +
  "\n" +
  "| abc | def |\n" +
  "| --- | --- |\n" +
  "| *abc* | **def** |\n" +
  "| abc | def |\n" +
  "\n" +
  "### 表格3\n" +
  "\n" +
  "名称 | 缩写\n" +
  "--- | ---\n" +
  "JavaScript | js\n" +
  "Python | py\n" +
  "C++ | cpp\n" +
  "\n" +
  "### 表格4\n" +
  "\n" +
  "| 题号 | 标题 | 难易度 |\n" +
  "| :--- | ---:| :---: |\n" +
  "| 1 | 两数之和 | 简单 |\n" +
  "| 15 | 三数之和 | 中等 |\n" +
  "| 262 | 行程和用户 | 困难 |\n" +
  "\n" +
  "### 表格5\n" +
  "\n" +
  "| 题号 | 标题 | 难易度 | 难易度 | 难易度 | 难易度 | 难易度 | 难易度 | 难易度 | 难易度 | 难易度 | 难易度 | 难易度 |\n" +
  "| :--- | ---:| :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: |\n" +
  "| 1 | 两数之和 | 简单 | 简单 | 简单 | 简单 | 简单 | 简单 | 简单 | 简单 | 简单 | 简单 | 简单 |\n" +
  "| 15 | 三数之和 | 中等 | 中等 | 中等 | 中等 | 中等 | 中等 | 中等 | 中等 | 中等 | 中等 | 中等 |\n" +
  "| 262 | 行程和用户 | 困难 | 困难 | 困难 | 困难 | 困难 | 困难 | 困难 | 困难 | 困难 | 困难 | 困难 |\n" +
  "\n" +
  "### 表格6\n" +
  "\n" +
  "| 题号 | 标题 | 难易度 |\n" +
  "| :--- | ---:| :---: |\n" +
  "| 1 | 两数之和 | 简单 |\n" +
  "| 15 | 三数之和 | 中等 |\n" +
  "| 262 | 行程和用户 | 困难 |\n" +
  "\n" +
  "### 表格7\n" +
  "\n" +
  "| 题号 | 标题 | 难易度 |\n" +
  "| :--- | ---:| :---: |\n" +
  "| 1111111111111111111111111111111111111111111111111111111111111 | 两数之和 | 简单 |\n" +
  "| 15 | 三数之和三数之和三数之和三数之和三数之和三数之和三数之和三数之和三数之和三数之和三数之和三数之和三数之和三数之和三数之和三数之和三数之和 | 中等 |\n" +
  "| 262 | 行程和用户 | 困难困难困难困难困难困难困难困难困难困难困难困难困难困难困难困难困难困难困难困难困难困难困难 |\n" +
  "\n"
export let strLink="这个程序展示了C语言程序的基本结构，包含头文件包含、主函数定义和标准输出操作。建议使用任何C语言编译器（如GCC、Clang等）进行编译运行。\n" +
  "\n" +
  "[3](ZmlsZS1pZD0xNzQ1MzAzNjA3MTk1MTI3NCZmaWxlLW5hbWU9JUU3JUFFJTgwJUU3JTlGJUFEJUU0JUJCJThCJUU3JUJCJThEJUU2JTlEJUFEJUU1JUI3JTlFJUU5JTk3JUFFJUU3JUFEJTk0XzIwMjUwNDIyMTIxNDA1ODk1LnBkZg==)\n" +
  "\n" +
  "普通文本 [Markdown语法](https://markdown.com.cn)。 普通文本\n" +
  "\n" +
  "https://markdown.com.cn\n" +
  "\n" +
  "## 标题1 https://markdown.com.cn\n" +
  "## 标题2 [Markdown语法](https://markdown.com.cn)\n" +
  "代码说明：\n" +
  "1. `#include <stdio.h>`：包含标准输入输出库，提供printf函数的使用权限[ 1 ](https://blog.csdn.net/weixin_36185028/article/details/80308816)\n" +
  "2. `int main(void)`：程序入口函数，返回整型值\n" +
  "3. `printf(\"Hello World!\\n\")`：输出指定字符串，`\\n`表示换行符[ 2 ](https://blog.csdn.net/jianshuilan_0613/article/details/116160418)\n" +
  "4. `return 0;`：表示程序成功结束[Markdown语法](https://markdown.com.cn)\n" +
  "   编译运行：\n" +
  "\n" +
  "## 参考来源：\n" +
  "\n"

export let strBlockRerference="块引用\n" +
  "\n" +
  "> 块引用1\n" +
  ">\n" +
  "> 块引用2\n" +
  ">\n" +
  "> 块引用3\n" +
  ">\n" +
  "> 块引用4\n" +
  ">\n" +
  "> 块引用5\n" +
  "\n" +
  "块引用\n" +
  "\n" +
  "> 块引用\n" +
  ">>\n" +
  ">> 块引用1\n" +
  ">>>\n" +
  ">>> 块引用2\n" +
  ">>>>\n" +
  ">>>> 块引用3\n" +
  ">>>>>\n" +
  ">>>>> 块引用4\n" +
  ">>>>>>\n" +
  ">>>>>> 块引用5"

export let strList="### 无序列表1(前缀是-,段落)\n" +
  "\n" +
  "- 无序列表1-1\n" +
  "- 无序列表1-2\n" +
  "- 无序列表1-3\n" +
  "- 无序列表1-4\n" +
  "- 无序列表1-5\n" +
  "- 无序列表1-6\n" +
  "\n" +
  "### 无序列表2(前缀是*,段落)\n" +
  "\n" +
  "* 无序列表2-1\n" +
  "* 无序列表2-2\n" +
  "* 无序列表2-3\n" +
  "* 无序列表2-4\n" +
  "* 无序列表2-5\n" +
  "* 无序列表2-6\n" +
  "\n" +
  "### 无序列表3(前缀是+,段落)\n" +
  "\n" +
  "+ 无序列表3-1\n" +
  "+ 无序列表3-2\n" +
  "+ 无序列表3-3\n" +
  "+ 无序列表3-4\n" +
  "+ 无序列表3-5\n" +
  "+ 无序列表3-6\n" +
  "\n" +
  "### 无序列表4(超长内容,段落)\n" +
  "\n" +
  "* 无序列表4-1。超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度\n" +
  "* 无序列表4-2。超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度\n" +
  "* 无序列表4-3。超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度\n" +
  "* 无序列表4-4。超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度\n" +
  "* 无序列表4-5。超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度\n" +
  "* 无序列表4-6。超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度超级长度\n"

export let strInlineCode="内联代码\n" +
  "\n" +
  "文本内容`内联代码`文本内容\n" +
  "\n" +
  "### 文本内容`内联代码`文本内容\n" +
  "\n" +
  "文本内容`超长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长内联代码`文本内容\n" +
  "\n" +
  "### 文本内容`超长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长内联代码`文本内容\n" +
  "\n" +
  "1. 文本内容`内联代码`文本内容\n" +
  "2. 文本内容`超长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长长内联代码`文本内容\n" +
  "\n" +
  "| 文本内容`内联代码`文本内容 | 文本内容`内联代码`文本内容 | 文本内容`内联代码`文本内容 |\n" +
  "|:---------------|---------------:|:--------------:|\n" +
  "| 文本内容`内联代码`文本内容 | 文本内容`内联代码`文本内容 | 文本内容`内联代码`文本内容 |\n" +
  "| 文本内容`内联代码`文本内容 | 文本内容`内联代码`文本内容 | 文本内容`内联代码`文本内容 |\n" +
  "| 文本内容`内联代码`文本内容 | 文本内容`内联代码`文本内容 | 文本内容`内联代码`文本内容 |"

export let strIndentedCodeBlock="缩进代码块\n" +
  "\n" +
  "    setPlugin(): MarkdownPlugin {\n" +
  "        let a = new MarkdownPlugin()\n" +
  "        a.setIsTablePlugin(true)\n" +
  "        a.setIsLatexMathPlugin(true)\n" +
  "        return a\n" +
  "    }\n" +
  "\n"

export let strFencedCodeBlock="```cangjie\n" +
  "setPlugin(): MarkdownPlugin {\n" +
  "    let a = new MarkdownPlugin()\n" +
  "    a.setIsTablePlugin(true)\n" +
  "    a.setIsLatexMathPlugin(true)\n" +
  "    return a\n" +
  "}\n" +
  "```"

export let strCombinedCodeBlock ="```java []\n" +
  "public class Main {\n" +
  "    public static void main(String[] args) {\n" +
  "        System.out.print(\"你好力扣\");\n" +
  "    }\n" +
  "}\n" +
  "```\n" +
  "```python []\n" +
  "print \"你好力扣\"\n" +
  "```\n" +
  "```html []\n" +
  "<img src=\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==\" alt=\"Red dot\" />\n" +
  "<img src='data:image/svg+xml,<svg xmlns=\"http://www.w3.org/2000/svg\" aria-hidden=\"true\" x=\"0px\" y=\"0px\" viewBox=\"0 0 100 100\" width=\"15\" height=\"15\" class=\"icon outbound\"><path fill=\"currentColor\" d=\"M18.8,85.1h56l0,0c2.2,0,4-1.8,4-4v-32h-8v28h-48v-48h28v-8h-32l0,0c-2.2,0-4,1.8-4,4v56C14.8,83.3,16.6,85.1,18.8,85.1z\"></path> <polygon fill=\"currentColor\" points=\"45.7,48.7 51.3,54.3 77.2,28.5 77.2,37.2 85.2,37.2 85.2,14.9 62.8,14.9 62.8,22.9 71.5,22.9\"></polygon></svg>' >\n" +
  "```\n" +
  "```json []\n" +
  "{\n" +
  "  \"firstName\": \"John\",\n" +
  "  \"lastName\": \"Smith\",\n" +
  "  \"age\": 25\n" +
  "}\n" +
  "```"

export let strAudio="音频\n" +
  "\n" +
  "![](https://qncdn.n.cn/so/upfile/8bb2e56621119eff26b21cdf90ad849f.mp3)\n" +
  "\n" +
  "![](https://qncdn.n.cn/so/upfile/夕阳无限好.mp3)\n" +
  "音频"

export let strVideo="视频\n" +
  "\n" +
  "![](https://psd.n.cn/aiso-vod/prod/image_video/202506/GwvyRjShNMe.mp4)\n" +
  "\n" +
  "视频"

export let strImage="网络图片\n" +
  "\n" +
  "1111![](https://qcdn2.zhaomi.cn/d/ptyGRnnvhwP_vlyRrwOPHhp_mark.png)1111\n" +
  "\n" +
  "2222![图片名称1](https://pic.leetcode-cn.com/1614477066-YeEeWg-file_1614477068523)2222\n" +
  "\n" +
  "![](https://qcdn2.zhaomi.cn/d/ptyGRnnvhwP_vlyRrwOPHhp_mark.png)\n" +
  "\n" +
  "![图片名称1](https://pic.leetcode-cn.com/1614477066-YeEeWg-file_1614477068523)\n" +
  "\n" +
  "![图片名称2](https://pic.leetcode-cn.com/1614477066-byZRdJ-file_1614477068721)\n" +
  "\n" +
  "![图片名称3](https://pic.leetcode-cn.com/1614477066-olRayu-file_1614477068738)\n" +
  "\n" +
  "本地rawfile图片\n" +
  "\n" +
  "![图片名称3](./001.svg)\n" +
  "\n" +
  "![图片名称3](./002.png)\n" +
  "\n" +
  "![图片名称3](./003.png)\n" +
  "\n" +
  "1111![图片名称3](./001.svg)111\n" +
  "\n" +
  "1111![图片名称3](./002.png)1111\n" +
  "\n" +
  "1111![图片名称3](./003.png)1111\n" +
  "\n" +
  "网络样式图片\n" +
  "\n" +
  "![image.png](https://pic.lingkou.xyz/1697707152-SaQbJz-image.png){:width=100}\n" +
  "\n" +
  "![image.png](https://pic.lingkou.xyz/1697707152-SaQbJz-image.png){:width=200}\n" +
  "\n" +
  "111 ![image.png](https://pic.lingkou.xyz/1697707152-SaQbJz-image.png){:width=100}\n" +
  "\n" +
  "111 ![image.png](https://pic.lingkou.xyz/1697707152-SaQbJz-image.png){:width=200}\n" +
  "\n" +
  "本地样式rawfile图片\n" +
  "\n" +
  "![图片名称3](./001.svg){:width=100}\n" +
  "\n" +
  "![图片名称3](./001.svg){:width=200}\n" +
  "\n" +
  "1111 ![图片名称3](./001.svg){:width=100}\n" +
  "\n" +
  "1111 ![图片名称3](./001.svg){:width=200}"

export let strBanner="### 无序列表12(嵌套图片Banner)\n" +
  "\n" +
  "*  Open the file.\n" +
  "*  Find the following code block on line 21:\n" +
  "\n" +
  "   <![图片名称1](https://pic.leetcode-cn.com/1614477066-YeEeWg-file_1614477068523),![图片名称2](https://pic.leetcode-cn.com/1614477066-byZRdJ-file_1614477068721),![图片名称3](https://pic.leetcode-cn.com/1614477066-olRayu-file_1614477068738)>\n" +
  "\n" +
  "*  Update the title to match the name of your website.\n" +
  "\n" +
  "\n" +
  "### 单独Banner\n" +
  "<![图片名称1](https://pic.leetcode-cn.com/1614477066-YeEeWg-file_1614477068523),![图片名称2](https://pic.leetcode-cn.com/1614477066-byZRdJ-file_1614477068721),![图片名称3](https://pic.leetcode-cn.com/1614477066-olRayu-file_1614477068738)>"